### PR TITLE
OpenShift Applier Deployment of Project

### PR DESCRIPTION
**Pull request by sabre1041**
Adds support to deploy the project using the [openshift-applier](https://github.com/redhat-cop/openshift-applier)

Follow instructions on the README to test

### CODE REVIEW

**Comment by elmiko** [comment]
thanks for the pr Andrew, i'm not familiar with the openshift-applier project. i am curious how a user would change the variables to the applications? (ie KAFKA_BROKERS to the air-traffic-control)

**Comment by sabre1041** [comment]
@elmiko A new [template](https://github.com/sabre1041/late-departures/blob/applier/applier/templates/air-traffic-control-deployment.yml) was created that will deploy the applications. A [parameter file](https://github.com/sabre1041/late-departures/blob/applier/applier/params/air-traffic-control-deployment) controls the variables that are injected into the template. Finally, the template is instantiated through the applier tool [here](https://github.com/sabre1041/late-departures/blob/applier/applier/inventory/group_vars/all.yml#L24-L31)

**Comment by elmiko** [comment]
thanks for the description, i figured it had something to do with those files. would you mind just adding a note to the readme about the parameter files. i will test this today and hopefully we can merge without much issue.

**Comment by sabre1041** [comment]
@elmiko ive updated the README

**Comment by elmiko** [comment]
tested this out and everything worked well on my end. thanks for the contribution @sabre1041 !

**Pull request merged**
